--- #YAML:1.0
name:                       Task-Labyrinth-Plugin-Music
version:                    1.00
abstract:                   All music related Labyrinth modules all at once
author:
  - Barbie <barbie@cpan.org>

license:                    artistic_2
distribution_type:          module
installdirs:                site

requires:
  perl:                                   5.006
  Labyrinth:                              5.21
  Labyrinth::Plugin::Articles::Lyrics:    1.00
  Labyrinth::Plugin::Articles::Profiles:  1.00
  Labyrinth::Plugin::Core:                5.15
  Labyrinth::Plugin::Event:               1.04
  Labyrinth::Plugin::Event::Types:        1.04
  Labyrinth::Plugin::Event::Venues:       1.04
  Labyrinth::Plugin::MP3s:                1.00
  Labyrinth::Plugin::Release:             0.01
recommends:
  Test::CPAN::Meta:                       0
  Test::CPAN::Meta::JSON:                 0
  Test::Pod:                              1.00
  Test::Pod::Coverage:                    0.08
build_requires:
  IO::File:                               0
  Test::More:                             0.70

provides:
  Task::Labyrinth::Plugin::Music:
    file:     lib/Task/Labyrinth/Plugin/Music.pm
    version:  1.00

no_index:
  directory:
    - examples
    - t
    - vhost

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  homepage:   http://labyrinth.missbarbell.co.uk
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Task-Labyrinth-Plugin-Music
  repository: http://github.com/barbie/task-labyrinth-plugin-music

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
